Add support for restoring recovery partition
Signed-off-by: Ed Beroset <beroset@ieee.org>

diff --git a/watch-image b/watch-image
--- a/watch-image
+++ b/watch-image
@@ -26,6 +26,8 @@ declare -a devices=("anthias" "bass" "beluga" "catfish" "dory" "firefish" "harmo
 save=false
 # assume we're not restoring
 restore=false
+# assume we're not restoring the recovery partition
+recovery=false
 # assume we're not in dryrun mode
 dryrun=false
 # assume we're not in quiet mode
@@ -44,14 +46,15 @@ Available options:
 -d or --dissect     separates previously saved image into one file per partition
 -h or --help        prints this help screen and quits
 -a or --adb         uses ADB command to communicate with watch
--p or --port    specifies a port to use for ssh and scp commands
--R or --remote  specifies the remote (watch)  name or address for ssh and scp commands
+-p or --port        specifies a port to use for ssh and scp commands
+-R or --remote      specifies the remote (watch)  name or address for ssh and scp commands
 -i or --image FN    uses FN as the file name of the image
 -r or --restore     restore the boot partition of the watch
 -s or --save        save the entire watch image (may be 4G or more!)
 -q or --quiet       don't emit messages describing the action
 -N or --dryrun      don't actually flash, just show what would happen
 -v or --version     displays the version of this program
+-y or --recovery    restore the recovery partition of the watch
 
 EOF
 }
@@ -88,7 +91,12 @@ function restorePartition {
     mapfile -t parts < <(getParts "${imagefile}")
     IFS=" " read -r -a mypart <<< "$(findPart "${whichpart}" "${parts[@]}")"
     if [ "${ADB}" = true ] ; then
-        echo "Restoration of partition is not yet supported in ADB mode."
+        if [ "${dryrun}" = "true" ] ; then
+            echo "I would have written the ${mypart[3]} partition (starting at ${mypart[1]}, containing ${mypart[2]} sectors) to ${mypart[0]}"
+        else
+            [ "${quiet}" = "true" ] || echo "Writing the ${mypart[3]} partition (starting at ${mypart[1]}, containing ${mypart[2]} sectors) to ${mypart[0]}"
+            dd if="${imagefile}" skip="${mypart[1]}" count="${mypart[2]}" | adb shell "su -c 'echo ${mypart[0]}'"
+        fi
     else
         if [ "${dryrun}" = "true" ] ; then
             echo "I would have written the ${mypart[3]} partition (starting at ${mypart[1]}, containing ${mypart[2]} sectors) to ${mypart[0]}"
@@ -179,6 +187,10 @@ while [[ $# -gt 0 ]] ; do
             showVersion
             shift
             ;;
+        -y|--recovery)
+            recovery=true
+            shift
+            ;;
         *)
             for device in "${devices[@]}"; do
                 [ "$1" == "${device}" ] && valid=true
@@ -225,6 +237,14 @@ if [ "${restore}" = "true" ] ; then
         exit 2
     fi
     restorePartition "boot" "${imagefile}"
+fi
+
+if [ "${recovery}" = "true" ] ; then
+    if [[ ! -f ${imagefile} ]] ; then
+        echo "Error: ${imagefile} does not exist"
+        exit 2
+    fi
+    restorePartition "recovery" "${imagefile}"
 fi
 
 if [ "${dissect}" = "true" ] ; then
